packages:
  - apps/*
  - packages/*

allowBuilds:
  cpu-features: false
  esbuild: true
  protobufjs: false
  sharp: true
  ssh2: false
  workerd: true

minimumReleaseAgeExclude:
  - hono@4.12.30
  - '@hono/zod-openapi@1.5.0'
