import type { ProjectState, ProjectTask } from "@earned-signal/application";

const baselineTasks: readonly ProjectTask[] = [
  {
    id: "A1",
    wbs: "1.1",
    name: "Confirm launch requirements",
    owner: "Maya Chen",
    durationWorkingDays: 5,
    measurementMethod: "PHYSICAL_PERCENT",
    predecessorId: null,
    budget: 600_000,
    progressPercent: 0,
    actualCost: 0,
    actualMinutes: 0,
  },
  {
    id: "A2",
    wbs: "1.2",
    name: "Approve experience flows",
    owner: "Leo Martin",
    durationWorkingDays: 4,
    measurementMethod: "PHYSICAL_PERCENT",
    predecessorId: "A1",
    budget: 400_000,
    progressPercent: 0,
    actualCost: 0,
    actualMinutes: 0,
  },
  {
    id: "A3",
    wbs: "2.1",
    name: "Build account API",
    owner: "Noah Williams",
    durationWorkingDays: 6,
    measurementMethod: "PHYSICAL_PERCENT",
    predecessorId: "A1",
    budget: 900_000,
    progressPercent: 0,
    actualCost: 0,
    actualMinutes: 0,
  },
  {
    id: "A4",
    wbs: "2.2",
    name: "Build customer workspace",
    owner: "Leo Martin",
    durationWorkingDays: 8,
    measurementMethod: "PHYSICAL_PERCENT",
    predecessorId: "A2",
    budget: 950_000,
    progressPercent: 0,
    actualCost: 0,
    actualMinutes: 0,
  },
  {
    id: "A5",
    wbs: "2.3",
    name: "Integrate UI and API",
    owner: "Noah Williams",
    durationWorkingDays: 5,
    measurementMethod: "PHYSICAL_PERCENT",
    predecessorId: "A4",
    budget: 650_000,
    progressPercent: 0,
    actualCost: 0,
    actualMinutes: 0,
  },
  {
    id: "A6",
    wbs: "2.4",
    name: "Prepare customer data",
    owner: "Maya Chen",
    durationWorkingDays: 4,
    measurementMethod: "PHYSICAL_PERCENT",
    predecessorId: "A3",
    budget: 350_000,
    progressPercent: 0,
    actualCost: 0,
    actualMinutes: 0,
  },
  {
    id: "A7",
    wbs: "3.1",
    name: "Run acceptance testing",
    owner: "Maya Chen",
    durationWorkingDays: 5,
    measurementMethod: "PHYSICAL_PERCENT",
    predecessorId: "A5",
    budget: 500_000,
    progressPercent: 0,
    actualCost: 0,
    actualMinutes: 0,
  },
  {
    id: "A8",
    wbs: "3.2",
    name: "Train support team",
    owner: "Leo Martin",
    durationWorkingDays: 3,
    measurementMethod: "PHYSICAL_PERCENT",
    predecessorId: "A6",
    budget: 250_000,
    progressPercent: 0,
    actualCost: 0,
    actualMinutes: 0,
  },
  {
    id: "A9",
    wbs: "3.3",
    name: "Launch customer portal",
    owner: "Noah Williams",
    durationWorkingDays: 1,
    measurementMethod: "PHYSICAL_PERCENT",
    predecessorId: "A7",
    budget: 100_000,
    progressPercent: 0,
    actualCost: 0,
    actualMinutes: 0,
  },
];

export const baselineProject: ProjectState = {
  id: "customer-portal-launch",
  name: "Customer portal launch",
  projectStart: "2026-07-13",
  statusDate: "2026-08-07",
  currency: "JPY",
  tasks: baselineTasks,
};

const currentOverrides: Readonly<Record<string, Partial<ProjectTask>>> = {
  A1: { progressPercent: 100, actualCost: 650_000, actualMinutes: 2_760 },
  A2: { progressPercent: 100, actualCost: 450_000, actualMinutes: 2_100 },
  A3: { durationWorkingDays: 7, progressPercent: 65, actualCost: 800_000, actualMinutes: 4_080 },
  A4: { durationWorkingDays: 10, progressPercent: 45, actualCost: 700_000, actualMinutes: 3_660 },
  A5: { durationWorkingDays: 6, progressPercent: 10, actualCost: 100_000, actualMinutes: 720 },
  A6: { progressPercent: 20, actualCost: 120_000, actualMinutes: 960 },
};

export const initialProject: ProjectState = {
  ...baselineProject,
  tasks: baselineTasks.map((task) => ({ ...task, ...currentOverrides[task.id] })),
};
