import type { ProjectState, ProjectTask } from "@earned-signal/application";

const baselineTasks: readonly ProjectTask[] = [
  {
    id: "A1",
    wbs: "1.1",
    wbsParentId: "G1",
    name: "Confirm launch requirements",
    owner: "Maya Chen",
    durationWorkingDays: 5,
    measurementMethod: "PHYSICAL_PERCENT",
    calendarId: "delivery",
    dependencies: [],
    constraint: null,
    budget: 600_000,
    progressPercent: 0,
    actualCost: 0,
    actualMinutes: 0,
  },
  {
    id: "A2",
    wbs: "1.2",
    wbsParentId: "G1",
    name: "Approve experience flows",
    owner: "Leo Martin",
    durationWorkingDays: 4,
    measurementMethod: "PHYSICAL_PERCENT",
    calendarId: "delivery",
    dependencies: [{ predecessorId: "A1", type: "FS", lagWorkingDays: 0 }],
    constraint: null,
    budget: 400_000,
    progressPercent: 0,
    actualCost: 0,
    actualMinutes: 0,
  },
  {
    id: "A3",
    wbs: "2.1",
    wbsParentId: "G2",
    name: "Build account API",
    owner: "Noah Williams",
    durationWorkingDays: 6,
    measurementMethod: "PHYSICAL_PERCENT",
    calendarId: "delivery",
    dependencies: [{ predecessorId: "A1", type: "FS", lagWorkingDays: 0 }],
    constraint: null,
    budget: 900_000,
    progressPercent: 0,
    actualCost: 0,
    actualMinutes: 0,
  },
  {
    id: "A4",
    wbs: "2.2",
    wbsParentId: "G2",
    name: "Build customer workspace",
    owner: "Leo Martin",
    durationWorkingDays: 8,
    measurementMethod: "PHYSICAL_PERCENT",
    calendarId: "delivery",
    dependencies: [
      { predecessorId: "A2", type: "FS", lagWorkingDays: 0 },
      { predecessorId: "A3", type: "SS", lagWorkingDays: 2 },
    ],
    constraint: null,
    budget: 950_000,
    progressPercent: 0,
    actualCost: 0,
    actualMinutes: 0,
  },
  {
    id: "A5",
    wbs: "2.3",
    wbsParentId: "G2",
    name: "Integrate UI and API",
    owner: "Noah Williams",
    durationWorkingDays: 5,
    measurementMethod: "PHYSICAL_PERCENT",
    calendarId: "delivery",
    dependencies: [
      { predecessorId: "A4", type: "FS", lagWorkingDays: 0 },
      { predecessorId: "A3", type: "FF", lagWorkingDays: 1 },
    ],
    constraint: null,
    budget: 650_000,
    progressPercent: 0,
    actualCost: 0,
    actualMinutes: 0,
  },
  {
    id: "A6",
    wbs: "2.4",
    wbsParentId: "G2",
    name: "Prepare customer data",
    owner: "Maya Chen",
    durationWorkingDays: 4,
    measurementMethod: "PHYSICAL_PERCENT",
    calendarId: "delivery",
    dependencies: [{ predecessorId: "A3", type: "FS", lagWorkingDays: 0 }],
    constraint: null,
    budget: 350_000,
    progressPercent: 0,
    actualCost: 0,
    actualMinutes: 0,
  },
  {
    id: "A7",
    wbs: "3.1",
    wbsParentId: "G3",
    name: "Run acceptance testing",
    owner: "Maya Chen",
    durationWorkingDays: 5,
    measurementMethod: "PHYSICAL_PERCENT",
    calendarId: "delivery",
    dependencies: [{ predecessorId: "A5", type: "FS", lagWorkingDays: 0 }],
    constraint: null,
    budget: 500_000,
    progressPercent: 0,
    actualCost: 0,
    actualMinutes: 0,
  },
  {
    id: "A8",
    wbs: "3.2",
    wbsParentId: "G3",
    name: "Train support team",
    owner: "Leo Martin",
    durationWorkingDays: 3,
    measurementMethod: "PHYSICAL_PERCENT",
    calendarId: "support",
    dependencies: [{ predecessorId: "A6", type: "FS", lagWorkingDays: 0 }],
    constraint: null,
    budget: 250_000,
    progressPercent: 0,
    actualCost: 0,
    actualMinutes: 0,
  },
  {
    id: "A9",
    wbs: "3.3",
    wbsParentId: "G3",
    name: "Launch customer portal",
    owner: "Noah Williams",
    durationWorkingDays: 1,
    measurementMethod: "PHYSICAL_PERCENT",
    calendarId: "delivery",
    dependencies: [
      { predecessorId: "A7", type: "FS", lagWorkingDays: 0 },
      { predecessorId: "A8", type: "FF", lagWorkingDays: 0 },
    ],
    constraint: { type: "FINISH_NO_LATER_THAN", date: "2026-08-31" },
    budget: 100_000,
    progressPercent: 0,
    actualCost: 0,
    actualMinutes: 0,
  },
];

export const baselineProject: ProjectState = {
  id: "customer-portal-launch",
  name: "Customer portal launch",
  projectStart: "2026-07-13",
  statusDate: "2026-08-07",
  currency: "JPY",
  defaultCalendarId: "delivery",
  calendars: [
    {
      id: "delivery",
      name: "Delivery · Mon–Fri",
      workingWeekdays: [1, 2, 3, 4, 5],
      nonWorkingDates: ["2026-07-20", "2026-08-11"],
    },
    {
      id: "support",
      name: "Support · Tue–Sat",
      workingWeekdays: [2, 3, 4, 5, 6],
      nonWorkingDates: ["2026-08-11"],
    },
  ],
  wbsGroups: [
    { id: "G1", parentId: null, code: "1", name: "Discover" },
    { id: "G2", parentId: null, code: "2", name: "Build" },
    { id: "G3", parentId: null, code: "3", name: "Launch" },
  ],
  tasks: baselineTasks,
};

const currentOverrides: Readonly<Record<string, Partial<ProjectTask>>> = {
  A1: { progressPercent: 100, actualCost: 650_000, actualMinutes: 2_760 },
  A2: { progressPercent: 100, actualCost: 450_000, actualMinutes: 2_100 },
  A3: { durationWorkingDays: 7, progressPercent: 65, actualCost: 800_000, actualMinutes: 4_080 },
  A4: { durationWorkingDays: 10, progressPercent: 45, actualCost: 700_000, actualMinutes: 3_660 },
  A5: { durationWorkingDays: 6, progressPercent: 10, actualCost: 100_000, actualMinutes: 720 },
  A6: { progressPercent: 20, actualCost: 120_000, actualMinutes: 960 },
};

export const initialProject: ProjectState = {
  ...baselineProject,
  tasks: baselineTasks.map((task) => ({ ...task, ...currentOverrides[task.id] })),
};
